version: 2.1

orbs:
  general-platform-helpers: atko-devices/eng-services-platform-helpers-general@2

parameters:
  ruby-version:
    type: string
    default: "3.2.2"
  xcode-version:
    type: string
    default: "14.3.1"

executors:
  apple-ci-m1-medium:
    macos:
      xcode: <<pipeline.parameters.xcode-version>>
    resource_class: macos.m1.medium.gen1

workflows:
  semgrep:
    jobs:
      - general-platform-helpers/job-semgrep-prepare:
          name: semgrep-prepare
      - general-platform-helpers/job-semgrep-scan:
          name: "Scan with Semgrep"
          requires:
            - semgrep-prepare
  build-and-test:
    jobs:
      - unit-test-ios
      - unit-test-macos


jobs:
  unit-test-ios:
    executor: apple-ci-m1-medium
    steps:
      - checkout
      - run:
          name: "Unit Tests iOS"
          command: set -o pipefail && xcodebuild -project OktaJWT.xcodeproj -scheme "OktaJWTLib_iOS" -destination "platform=iOS Simulator,OS=latest,name=iPhone 11" clean test | xcpretty

  unit-test-macos:
    executor: apple-ci-m1-medium
    steps:
      - checkout
      - run:
          name: "Unit Tests macOS"
          command: set -o pipefail && xcodebuild -project OktaJWT.xcodeproj -scheme "OktaJWTLib_macOS" -destination "platform=macOS" clean test | xcpretty
