version: 2.1

orbs:
  general-platform-helpers: okta/general-platform-helpers@1.9

workflows:
  semgrep:
    jobs:
      - general-platform-helpers/job-semgrep-scan:
          name: "Scan with Semgrep"
          context:
            - static-analysis
